-- V112 Family Gallery: per-photo reactions and comments.
-- Run once using Supabase SQL Editor. Does not modify Family Album photo tables.
create table if not exists public.gallery_photo_likes (
 photo_id bigint not null references public.gallery(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 reaction text not null default 'like' check (reaction in ('like','love','care','haha','wow','sad')),
 created_at timestamptz not null default now(),
 primary key(photo_id,user_id)
);
create table if not exists public.gallery_photo_comments (
 id bigint generated by default as identity primary key,
 photo_id bigint not null references public.gallery(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 content text not null check (char_length(btrim(content)) between 1 and 500),
 created_at timestamptz not null default now()
);
create index if not exists gallery_photo_comments_photo_id_created_idx on public.gallery_photo_comments(photo_id,created_at);
alter table public.gallery_photo_likes enable row level security;
alter table public.gallery_photo_comments enable row level security;
grant select,insert,update,delete on public.gallery_photo_likes to authenticated;
grant select,insert,update,delete on public.gallery_photo_comments to authenticated;
grant usage, select on all sequences in schema public to authenticated;
drop policy if exists gallery_photo_likes_member_read on public.gallery_photo_likes;
create policy gallery_photo_likes_member_read on public.gallery_photo_likes for select to authenticated using (exists (select 1 from public.gallery g where g.id=photo_id));
drop policy if exists gallery_photo_likes_member_insert on public.gallery_photo_likes;
create policy gallery_photo_likes_member_insert on public.gallery_photo_likes for insert to authenticated with check (user_id=auth.uid() and exists (select 1 from public.gallery g where g.id=photo_id));
drop policy if exists gallery_photo_likes_member_update on public.gallery_photo_likes;
create policy gallery_photo_likes_member_update on public.gallery_photo_likes for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
drop policy if exists gallery_photo_likes_member_delete on public.gallery_photo_likes;
create policy gallery_photo_likes_member_delete on public.gallery_photo_likes for delete to authenticated using (user_id=auth.uid());
drop policy if exists gallery_photo_comments_member_read on public.gallery_photo_comments;
create policy gallery_photo_comments_member_read on public.gallery_photo_comments for select to authenticated using (exists (select 1 from public.gallery g where g.id=photo_id));
drop policy if exists gallery_photo_comments_member_insert on public.gallery_photo_comments;
create policy gallery_photo_comments_member_insert on public.gallery_photo_comments for insert to authenticated with check (user_id=auth.uid() and exists (select 1 from public.gallery g where g.id=photo_id));
drop policy if exists gallery_photo_comments_member_delete on public.gallery_photo_comments;
create policy gallery_photo_comments_member_delete on public.gallery_photo_comments for delete to authenticated using (user_id=auth.uid());
