-- Duarte Clan V68: Story likes for desktop + mobile
create table if not exists public.family_story_likes (
  id bigint generated by default as identity primary key,
  story_id uuid not null references public.family_stories(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (story_id, user_id)
);

alter table public.family_story_likes enable row level security;

drop policy if exists "duarte_story_likes_read" on public.family_story_likes;
create policy "duarte_story_likes_read" on public.family_story_likes
for select to authenticated using (true);

drop policy if exists "duarte_story_likes_insert_own" on public.family_story_likes;
create policy "duarte_story_likes_insert_own" on public.family_story_likes
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "duarte_story_likes_delete_own" on public.family_story_likes;
create policy "duarte_story_likes_delete_own" on public.family_story_likes
for delete to authenticated using (auth.uid() = user_id);

grant select, insert, delete on public.family_story_likes to authenticated;
